### ISSUE TITLE
Generators Don't Work Upon Restarting

### ISSUE THREAD

**Issue by ReallyNotSomeone** [Intybyte/CustomItemGenerators#1]
Hi, I noticed that when I restarted my server, the generators stopped working. I'm not sure what the issue is, but they say idle, and won't recieve power, and even if they have power before the restart, it still doesn't generate.
https://pastebin.com/52LtPAy8
![image_2024-12-23_233951477](https://github.com/user-attachments/assets/41c3334b-0c9b-4d5c-a1aa-446bd0e51dad)

**Comment by Intybyte** [comment]
For those that have this issue download from modrinth not blod builds
